# Site settings
title: mathew woodyard 
email: "https://www.google.com/recaptcha/mailhide/d?k=01XRW-ilKwfnke1vB_a8b_Ig==&c=riTOhupE4L1XkWIBJgrF_EefWNGXLD0Hj-ddgeKAk70="
description: "Mathew Woodyard's personal web site."
baseurl: ""
url: "https://woodrad.com"
github: "https://github.com/woodrad"
jonx: "https://thejonx.github.io"
twitter: "woodrad"
blog: "https://blog.woodrad.com"
debsblog: "https://debsonsoftware.com"
resume: "https://woodrad.com/resume.html"

# Exclude things from _site/
exclude: [Gemfile, Gemfile.lock, Rakefile, README.md, LICENSE]

# Build settings
markdown: kramdown
